# Generated by Django 2.1.4 on 2020-02-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('lyric', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=100, null=True)),
                ('magnitude', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
